# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creation_date',
            new_name='date_created',
        ),
    ]
