# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 19:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160901_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Should be a 10 digit valid phone number', regex='^[789]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='aadhar',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_aadhar_number', message='Should be a 16 digit valid aadhar number', regex='^\\d{16}$')]),
        ),
    ]
