# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160904_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='given_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
