# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160904_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='given_by',
        ),
    ]
