# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-01 09:57
from __future__ import unicode_literals

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160901_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.Parent'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[account.models.phone_validator]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='aadhar',
            field=models.CharField(max_length=16, unique=True, validators=[account.models.aadhar_validator]),
        ),
    ]
