# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_task_given_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('U', 'Unscheduled Check Up'), ('S', 'Scheduled Check Up'), ('V', 'Vaccination')], default='U', max_length=1),
        ),
    ]
