# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160904_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reason',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
