# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20160904_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base', models.DurationField()),
                ('delta', models.DurationField()),
            ],
            options={
                'verbose_name': 'Vaccine',
            },
        ),
        migrations.AlterUniqueTogether(
            name='vaccine',
            unique_together=set([('name',)]),
        ),
    ]
